### ISSUE TITLE
Wrog path to resource

### ISSUE THREAD

**Issue by karol-bialkowski** [Jabob-tech/htdocs#1]
https://github.com/Jabob-tech/htdocs/blob/4c31c2f9f7042a762e44f5fa6112ed40c6a2b40a/html/index.html#L6

You should set the relative path relate to main resource on theserver. You don’t have directory like „d:/dokumenty/strona” etc. So, please change to „css\styles.css” instead of „\A Projekt\htdocs\css...”

after this fix, your assets can work on everywhere, not only „A Projekt” directory :)

**Comment by Jabob-tech** [comment]
I changed the paths and now it's fixed :)

**Comment by karol-bialkowski** [comment]
@Jabob-tech awesome ! You can backslash at the beginning andyou will avoid display wrong file. If you type:

css/file.css

The server find file.css in css directory which is in the current directory. The “current” is the key. If you create the new directory inside main project (pages) and create contact.html, server will find css like that: pages/css/style.css and you have css file:m there: css/style.css
