### ISSUE TITLE
Button instead input

### ISSUE THREAD

**Issue by karol-bialkowski** [Jabob-tech/htdocs#3]
https://github.com/Jabob-tech/htdocs/blob/4c31c2f9f7042a762e44f5fa6112ed40c6a2b40a/html/index.html#L23

Of you use <button type=submit> Element instead of input type submit because you can insert an additonal content into button ( like arrows, chevrons etc). Insert html elementa into input is not possible :) This is better solution :)

**Comment by Jabob-tech** [comment]
You're right. I've mended it :D

**Comment by karol-bialkowski** [comment]
@Jabob-tech did you update this? I can’t find the updated element :(

**Comment by Jabob-tech** [comment]
Yeah, it's in the 23rd line in the index.html file.

**Comment by Jabob-tech** [comment]
https://github.com/Jabob-tech/htdocs/blob/fce4342cea1a0926da5536aac7faa6f234b74da1/html/index.html#L23
