### ISSUE TITLE
Required param

### ISSUE THREAD

**Issue by karol-bialkowski** [Jabob-tech/htdocs#4]
https://github.com/Jabob-tech/htdocs/blob/4c31c2f9f7042a762e44f5fa6112ed40c6a2b40a/html/index.html#L21

If you append the ‚required’ param, you will have a simply front-end validation :) check out https://www.w3schools.com/tags/att_input_required.asp

**Comment by Jabob-tech** [comment]
Perfect idea, I fixed it :D

**Comment by karol-bialkowski** [comment]
@Jabob-tech please check your code everytime and reformat :) an extra space has been added :)

**Comment by Jabob-tech** [comment]
Oh, I see. Now it's deleted :D
